package catalog

import "github.com/watzon/caravan/internal/core"

// Standard Newznab blocks most commercial Usenet indexers advertise.
var usenetCategories = []int{1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000}

// presets are first-party catalog rows. Torrent *sites* live in sites.json;
// these are the sources that speak Newznab/Torznab natively, plus the generic
// Jackett / Prowlarr / Newznab / Torznab entries.
var presets = []Definition{
	{
		ID:             "jackett",
		Name:           "Jackett",
		Kind:           KindGeneric,
		Protocol:       core.IndexerTypeTorznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Any Jackett indexer via its Torznab feed. Replace INDEXER with the Jackett id.",
		InfoURL:        "https://github.com/Jackett/Jackett",
		URLPlaceholder: "http://127.0.0.1:9117/api/v2.0/indexers/INDEXER/results/torznab",
		RequiresAPIKey: true,
	},
	{
		ID:             "prowlarr",
		Name:           "Prowlarr",
		Kind:           KindGeneric,
		Protocol:       core.IndexerTypeTorznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "A single Prowlarr indexer via its Torznab feed. The path id is the Prowlarr indexer id.",
		InfoURL:        "https://wiki.servarr.com/prowlarr",
		URLPlaceholder: "http://127.0.0.1:9696/1/api",
		RequiresAPIKey: true,
	},
	{
		ID:             "generic-torznab",
		Name:           "Generic Torznab",
		Kind:           KindGeneric,
		Protocol:       core.IndexerTypeTorznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Any Torznab-compatible torrent indexer. Enter the API root without a query string.",
		URLPlaceholder: "http://127.0.0.1:9117/api/v2.0/indexers/INDEXER/results/torznab",
		RequiresAPIKey: true,
	},
	{
		ID:             "generic-newznab",
		Name:           "Generic Newznab",
		Kind:           KindGeneric,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Any Newznab-compatible Usenet indexer. Enter the API root without a query string.",
		URLPlaceholder: "https://indexer.example/api",
		RequiresAPIKey: true,
	},
	{
		ID:             "nzbhydra2",
		Name:           "NZBHydra2",
		Kind:           KindGeneric,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "An NZBHydra2 instance used as a Newznab source.",
		InfoURL:        "https://github.com/theotherp/nzbhydra2",
		URLPlaceholder: "http://127.0.0.1:5076/api",
		RequiresAPIKey: true,
	},

	{
		ID:             "abnzb",
		Name:           "abNZB",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://abnzb.com",
		URL:            "https://abnzb.com",
		RequiresAPIKey: true,
		Categories:     []int{2000, 3000, 4000, 5000, 6000, 7000, 8000},
	},
	{
		ID:             "althub",
		Name:           "altHUB",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://althub.co.za",
		URL:            "https://api.althub.co.za",
		RequiresAPIKey: true,
		Categories:     []int{2000, 3000, 4000, 5000, 7000},
	},
	{
		ID:             "dognzb",
		Name:           "DOGnzb",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://dognzb.cr",
		URL:            "https://api.dognzb.cr",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "drunkenslug",
		Name:           "DrunkenSlug",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://drunkenslug.com",
		URL:            "https://drunkenslug.com",
		RequiresAPIKey: true,
		Categories:     []int{1000, 2000, 3000, 4000, 5000, 6000, 7000},
	},
	{
		ID:             "gingadaddy",
		Name:           "GingaDADDY",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://www.gingadaddy.com",
		URL:            "https://www.gingadaddy.com",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "miatrix",
		Name:           "Miatrix",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://www.miatrix.com",
		URL:            "https://www.miatrix.com",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "newz69",
		Name:           "Newz69",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://newz69.keagaming.com",
		URL:            "https://newz69.keagaming.com",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "ninjacentral",
		Name:           "NinjaCentral",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://ninjacentral.co.za",
		URL:            "https://ninjacentral.co.za",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "nzblife",
		Name:           "Nzb.life",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzb.life",
		URL:            "https://api.nzb.life",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "nzbcat",
		Name:           "NZBCat",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzb.cat",
		URL:            "https://nzb.cat",
		RequiresAPIKey: true,
		Categories:     []int{1000, 2000, 3000, 4000, 5000, 6000, 7000},
	},
	{
		ID:             "nzbfinder",
		Name:           "NZBFinder",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzbfinder.ws",
		URL:            "https://nzbfinder.ws",
		RequiresAPIKey: true,
		Categories:     []int{2000, 3000, 5000, 6000, 7000},
	},
	{
		ID:             "nzbgeek",
		Name:           "NZBgeek",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzbgeek.info",
		URL:            "https://api.nzbgeek.info",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "nzbnoob",
		Name:           "NzbNoob",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://www.nzbnoob.com",
		URL:            "https://www.nzbnoob.com",
		RequiresAPIKey: true,
		Categories:     []int{2000, 3000, 4000, 5000, 6000, 7000, 8000},
	},
	{
		ID:             "nzbndx",
		Name:           "NZBNDX",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://www.nzbndx.com",
		URL:            "https://www.nzbndx.com",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "nzbplanet",
		Name:           "NzbPlanet",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzbplanet.net",
		URL:            "https://api.nzbplanet.net",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "nzbstars",
		Name:           "NZBStars",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzbstars.com",
		URL:            "https://nzbstars.com",
		RequiresAPIKey: true,
		Categories:     []int{1000, 2000, 3000, 4000, 5000, 6000, 7000},
	},
	{
		ID:             "nzbsu",
		Name:           "NZB.su",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://nzb.su",
		URL:            "https://api.nzb.su",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "omgwtfnzbs",
		Name:           "omgwtfnzbs",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://omgwtfnzbs.me",
		URL:            "https://api.omgwtfnzbs.me",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "spotweb",
		Name:           "Spotweb",
		Kind:           KindGeneric,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "A self-hosted Spotweb instance used as a Newznab source.",
		InfoURL:        "https://github.com/spotweb/spotweb",
		URLPlaceholder: "http://127.0.0.1/spotweb",
		RequiresAPIKey: true,
		Categories:     usenetCategories,
	},
	{
		ID:             "tabularasa",
		Name:           "Tabula Rasa",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPrivate,
		Language:       "en-US",
		Description:    "Private Usenet indexer.",
		InfoURL:        "https://www.tabula-rasa.pw",
		URL:            "https://www.tabula-rasa.pw/api/v1",
		RequiresAPIKey: true,
		Categories:     []int{1000, 2000, 3000, 4000, 5000, 6000, 7000},
	},

	{
		ID:           "thepiratebay",
		DefinitionID: "thepiratebay",
		Name:         "The Pirate Bay",
		Kind:         KindTorrent,
		Protocol:     core.IndexerTypeTorznab,
		Privacy:      PrivacyPublic,
		Language:     "en-US",
		Description:  "Public torrent search executed locally through Caravan's JSON adapter.",
		InfoURL:      "https://thepiratebay.org",
		URL:          "https://thepiratebay.org",
		URLs:         []string{"https://thepiratebay.org"},
		Categories:   []int{1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000},
		Settings: []Setting{{
			Name: "apiurl", Label: "Search API URL", Type: "text", Default: "https://apibay.org",
		}},
	},
	{
		ID:           "rutor",
		DefinitionID: "rutor",
		Name:         "RuTor",
		Kind:         KindTorrent,
		Protocol:     core.IndexerTypeTorznab,
		Privacy:      PrivacyPublic,
		Language:     "ru-RU",
		Description:  "Public Russian-language torrent search executed locally by Caravan.",
		InfoURL:      "https://rutor.info",
		URL:          "https://rutor.info",
		URLs:         []string{"https://rutor.info"},
		Categories:   []int{8000},
		Content:      []string{ContentOther},
	},
	{
		ID:           "nyaa",
		DefinitionID: "nyaa",
		MetadataID:   "nyaasi",
		Name:         "Nyaa",
		Kind:         KindTorrent,
		Protocol:     core.IndexerTypeTorznab,
		Privacy:      PrivacyPublic,
		Language:     "en-US",
		Description:  "Public Japanese-media torrent search executed locally by Caravan.",
		InfoURL:      "https://nyaa.si",
		URL:          "https://nyaa.si",
		URLs:         []string{"https://nyaa.si"},
		Categories:   []int{3000, 4000, 5000, 5070, 7000},
		Content:      []string{ContentTV, ContentAnime, ContentAudio, ContentBooks, ContentPC},
	},
	{
		ID:           "tokyotosho",
		DefinitionID: "tokyotosho",
		Name:         "TokyoTosho",
		Kind:         KindTorrent,
		Protocol:     core.IndexerTypeTorznab,
		Privacy:      PrivacyPublic,
		Language:     "en-US",
		Description:  "Public Japanese-media torrent search executed locally by Caravan.",
		InfoURL:      "https://www.tokyo-tosho.net",
		URL:          "https://www.tokyo-tosho.net",
		URLs:         []string{"https://www.tokyo-tosho.net"},
		Categories:   []int{3000, 5000, 5070, 6000, 7000, 8000},
		Content:      []string{ContentTV, ContentAnime, ContentAudio, ContentBooks, ContentAdult, ContentOther},
	},
	{
		ID:             "animetosho",
		Name:           "AnimeTosho",
		Kind:           KindTorrent,
		Protocol:       core.IndexerTypeTorznab,
		Privacy:        PrivacyPublic,
		Language:       "en-US",
		Description:    "Public anime NZB/DDL mirror with a native Torznab feed.",
		InfoURL:        "https://animetosho.org",
		URL:            "https://feed.animetosho.org",
		RequiresAPIKey: false,
		Categories:     []int{2020, 5070},
	},
	{
		ID:             "animetosho-usenet",
		Name:           "AnimeTosho (Usenet)",
		Kind:           KindUsenet,
		Protocol:       core.IndexerTypeNewznab,
		Privacy:        PrivacyPublic,
		Language:       "en-US",
		Description:    "AnimeTosho's Newznab feed of the same public anime archive.",
		InfoURL:        "https://animetosho.org",
		URL:            "https://feed.animetosho.org",
		RequiresAPIKey: false,
		Categories:     []int{2020, 5070},
	},
	{
		ID:             "torrentnetwork",
		Name:           "Torrent Network",
		Kind:           KindTorrent,
		Protocol:       core.IndexerTypeTorznab,
		Privacy:        PrivacyPrivate,
		Language:       "de-DE",
		Description:    "German private tracker with a native Torznab API.",
		InfoURL:        "https://tntracker.org",
		URL:            "https://tntracker.org/api/torznab",
		RequiresAPIKey: true,
	},
}
