package par2

import "fmt"

// GF(2^16) exactly as PAR2 defines it: the field generated by 0x1100B
// (x^16 + x^12 + x^3 + x + 1) with 2 as the generator element. par2cmdline
// spells this `typedef Galois<16,0x1100B,u16> Galois16`, and every constant
// below is chosen to reproduce its tables bit for bit — a field that differs
// from the reference in any detail produces recovery data that looks fine and
// restores garbage.

const (
	// gfOrder is the size of the field, and doubles as the carry bit the
	// table builder tests for.
	gfOrder = 1 << 16
	// gfLimit is the order of the multiplicative group: every non-zero
	// element satisfies x^gfLimit == 1.
	gfLimit = gfOrder - 1
	// gfPoly is the reduction polynomial, x^16 + x^12 + x^3 + x + 1.
	gfPoly = 0x1100B
	// maxInputSlices is how many distinct constants the field can supply,
	// and therefore the hard ceiling on the number of slices a par2 set may
	// describe. It is φ(65535) = 2·4·16·256.
	maxInputSlices = 32768
)

var (
	// gfLog[x] is the discrete log of x base 2. gfLog[0] is meaningless and
	// is never read: every caller guards a zero operand first.
	gfLog [gfOrder]uint16
	// gfExp is the antilog table, duplicated end to end so that mul and div
	// can index it with an unreduced sum or difference and skip a modulo in
	// the inner loop.
	gfExp [2 * gfLimit]uint16
	// gfConstants[i] is the field constant assigned to input slice i: the
	// (i+1)-th power of two whose exponent is coprime to 65535. The spec
	// phrases the constraint as "order 65535", which for a power of two means
	// an exponent not divisible by 3, 5, 17 or 257.
	gfConstants [maxInputSlices]uint16
)

func init() {
	b := uint32(1)
	for l := 0; l < gfLimit; l++ {
		gfLog[b] = uint16(l)
		gfExp[l] = uint16(b)
		gfExp[l+gfLimit] = uint16(b)
		b <<= 1
		if b&gfOrder != 0 {
			b ^= gfPoly
		}
	}

	n := 0
	for e := 1; n < maxInputSlices; e++ {
		if e%3 != 0 && e%5 != 0 && e%17 != 0 && e%257 != 0 {
			gfConstants[n] = gfExp[e]
			n++
		}
	}
}

// gfMul multiplies in the field.
func gfMul(a, b uint16) uint16 {
	if a == 0 || b == 0 {
		return 0
	}
	return gfExp[int(gfLog[a])+int(gfLog[b])]
}

// gfDiv divides in the field. Dividing by zero is a programming error and
// panics rather than returning a plausible-looking wrong answer; the only
// caller is matrix inversion, which checks its pivot first.
func gfDiv(a, b uint16) uint16 {
	if b == 0 {
		panic("par2: division by zero in GF(2^16)")
	}
	if a == 0 {
		return 0
	}
	return gfExp[int(gfLog[a])-int(gfLog[b])+gfLimit]
}

// gfInv is the multiplicative inverse.
func gfInv(a uint16) uint16 { return gfDiv(1, a) }

// gfPow raises a to the e-th power. e is the exponent carried by a recovery
// slice packet, so it is a full uint32 even though the field only cares about
// it modulo 65535.
func gfPow(a uint16, e uint32) uint16 {
	if e == 0 {
		return 1
	}
	if a == 0 {
		return 0
	}
	return gfExp[uint64(gfLog[a])*uint64(e)%gfLimit]
}

// sliceConstant is the field constant PAR2 assigns to the input slice at
// global index i. The second result is false when i is past the number of
// constants the field can supply.
func sliceConstant(i int) (uint16, bool) {
	if i < 0 || i >= maxInputSlices {
		return 0, false
	}
	return gfConstants[i], true
}

// mulAddSlice computes dst ^= factor * src over the slice data, reading both
// buffers as little-endian 16-bit words the way the spec requires. dst and src
// must be the same even length.
//
// This is the inner loop of both computing and consuming recovery data, so the
// log of the factor is hoisted out of it and the two degenerate factors get
// their own paths: factor 1 (which every exponent-zero recovery slice uses for
// every input) is a plain XOR.
func mulAddSlice(dst, src []byte, factor uint16) {
	if factor == 0 || len(src) == 0 {
		return
	}
	if len(dst) != len(src) {
		panic("par2: mulAddSlice length mismatch")
	}
	if factor == 1 {
		for i := range src {
			dst[i] ^= src[i]
		}
		return
	}
	lf := int(gfLog[factor])
	for i := 0; i+1 < len(src); i += 2 {
		v := uint16(src[i]) | uint16(src[i+1])<<8
		if v == 0 {
			continue
		}
		p := gfExp[lf+int(gfLog[v])]
		dst[i] ^= byte(p)
		dst[i+1] ^= byte(p >> 8)
	}
}

// invertMatrix inverts the n×n row-major matrix m over GF(2^16) by
// Gauss-Jordan elimination, leaving m untouched.
//
// par2cmdline asserts that this matrix is never singular and does no pivoting
// at all. That holds for the contiguous exponents it normally deals with, but
// a set assembled from whichever recovery volumes happened to arrive can hand
// us an arbitrary subset of exponents, and a generalised Vandermonde matrix
// over a field of characteristic two is not unconditionally invertible. So we
// pivot, and if the matrix really is singular we say so instead of dividing by
// zero and writing the result to disk.
func invertMatrix(m []uint16, n int) ([]uint16, error) {
	if n == 0 {
		return nil, nil
	}
	if len(m) != n*n {
		panic("par2: invertMatrix dimension mismatch")
	}

	a := make([]uint16, n*n)
	copy(a, m)
	inv := make([]uint16, n*n)
	for i := 0; i < n; i++ {
		inv[i*n+i] = 1
	}

	for col := 0; col < n; col++ {
		pivot := -1
		for row := col; row < n; row++ {
			if a[row*n+col] != 0 {
				pivot = row
				break
			}
		}
		if pivot < 0 {
			return nil, fmt.Errorf("%w: recovery matrix is singular at column %d", ErrRepairFailed, col)
		}
		if pivot != col {
			swapRows(a, n, pivot, col)
			swapRows(inv, n, pivot, col)
		}

		// Normalise the pivot row so the pivot becomes 1.
		if p := a[col*n+col]; p != 1 {
			ip := gfInv(p)
			scaleRow(a[col*n:col*n+n], ip)
			scaleRow(inv[col*n:col*n+n], ip)
		}

		// Clear the column everywhere else.
		for row := 0; row < n; row++ {
			if row == col {
				continue
			}
			f := a[row*n+col]
			if f == 0 {
				continue
			}
			addScaledRow(a[row*n:row*n+n], a[col*n:col*n+n], f)
			addScaledRow(inv[row*n:row*n+n], inv[col*n:col*n+n], f)
		}
	}
	return inv, nil
}

func swapRows(m []uint16, n, i, j int) {
	for k := 0; k < n; k++ {
		m[i*n+k], m[j*n+k] = m[j*n+k], m[i*n+k]
	}
}

func scaleRow(row []uint16, f uint16) {
	for i := range row {
		row[i] = gfMul(row[i], f)
	}
}

func addScaledRow(dst, src []uint16, f uint16) {
	for i := range dst {
		dst[i] ^= gfMul(src[i], f)
	}
}
