// Package par2 verifies and repairs par2 recovery sets: the integrity half of
// the embedded Usenet engine (SPEC §5.1, PLAN phase 7 task 4).
//
// A par2 set is a description of some files — their names, lengths, MD5s, and
// a checksum for every fixed-size slice of them — plus a pile of recovery
// slices computed as Reed-Solomon parity over the concatenated slices of all
// of those files. Given enough recovery slices, any equal number of damaged or
// missing source slices can be reconstructed exactly.
//
// # Fail loudly
//
// This package never repairs approximately. Every packet it reads must pass
// the MD5 the packet carries; every repaired file must match the MD5 the set
// declared for it before it is allowed to replace anything on disk; and a set
// that cannot cover the damage returns an [*InsufficientError] carrying the
// exact deficit rather than doing what it can. Repair math that is subtly
// wrong corrupts media silently (PLAN phase 7 risks) — a download that fails
// with "needs 12 blocks, have 7" is a good outcome, a file that plays for
// forty minutes and then does not is not.
//
// Repairs are also all-or-nothing. Reconstructed data is written to temporary
// files, every one of them is checked against its declared MD5, and only then
// is anything renamed into place. A failure part-way through leaves the
// directory exactly as it was found.
//
// # Reed-Solomon
//
// The field is GF(2^16) generated by 0x1100B (x^16 + x^12 + x^3 + x + 1) with
// 2 as the generator, and slice data is read as little-endian 16-bit words.
// Input slice i is assigned the constant 2^n where n is the (i+1)-th positive
// integer coprime to 65535 — that is, not divisible by 3, 5, 17 or 257 — and
// the recovery slice with exponent e is the sum over every input slice of
// constant_i^e times slice_i. Recovering m missing slices is therefore an m×m
// linear system over the field, which this package solves by Gauss-Jordan
// inversion.
//
// Specification: Parity Volume Set Specification 2.0,
// https://parchive.sourceforge.net/docs/specifications/parity-volume-spec/article-spec.html
// Cross-checked against par2cmdline 1.2.0, whose verdicts are frozen in
// testdata/MANIFEST.json.
//
// # Cost
//
// Verification is one pass over the source files. Repair reads every surviving
// slice once and does one field multiply-add per (surviving slice, missing
// slice) pair, which is the inherent cost of Reed-Solomon and is what makes
// repairing a badly damaged set slow.
//
// Peak memory is *twice* the slice size times the number of missing slices:
// the right-hand side of the linear system is held in full, and the solved
// slices are built beside it before either can be released. That product is
// unbounded — a 40 GB release at a 2 MB slice size with 10% loss would want
// eight gigabytes — so [MaxRepairMemory] caps it and a repair that would
// exceed the cap fails with [ErrRepairTooLarge] rather than being killed by
// the kernel halfway through. par2cmdline solves in chunks instead (its -m
// option); this package does not, and says so rather than pretending the
// budget is smaller than it is.
package par2

import (
	"errors"
	"fmt"
)

// Errors callers act on.
var (
	// ErrMalformed means the par2 files could not be understood: no main
	// packet, a packet whose MD5 does not cover its contents, a file
	// description missing for a file the main packet lists, a slice checksum
	// count that disagrees with the file length. It is not a damaged
	// download, it is a damaged (or foreign) par2 set.
	ErrMalformed = errors.New("par2: malformed par2 set")

	// ErrUnrepairable is the sentinel every "the damage exceeds the recovery
	// budget" failure unwraps to. Callers match on it to report the deficit
	// instead of retrying.
	ErrUnrepairable = errors.New("par2: not enough recovery blocks to repair")

	// ErrRepairFailed means the repair ran but produced data that does not
	// match what the set declared. Nothing is written to disk when this is
	// returned. It always indicates a bug or a par2 set that lies, never
	// ordinary damage — ordinary damage is ErrUnrepairable.
	ErrRepairFailed = errors.New("par2: repaired data failed its own checksum")

	// ErrUnsafeName means a par2 set names a file that would be written
	// outside the target directory. Such a set is rejected outright rather
	// than partially honoured.
	ErrUnsafeName = errors.New("par2: unsafe file name in par2 set")

	// ErrRepairTooLarge means the damage is inside the set's recovery budget
	// but outside this build's memory budget: solving it would hold more than
	// MaxRepairMemory at once. It is deliberately a different answer from
	// ErrUnrepairable — more recovery blocks would not help, and the release
	// is not damaged beyond saving — and it is deliberately an error rather
	// than an attempt, because being killed by the kernel halfway through a
	// repair tells the user nothing at all.
	ErrRepairTooLarge = errors.New("par2: repair needs more memory than this build will allocate")
)

// MaxRepairMemory bounds the two full sets of slice buffers a repair holds at
// once (see the package comment's cost note). A gigabyte is far above any
// repair a normal release produces and far below what would take a NAS down.
const MaxRepairMemory = 1 << 30

// maxRepairMemory is the limit actually enforced. It is a variable so a test
// can lower it to something a kilobyte-sized fixture can exceed, the same way
// the pipeline's flush threshold is; nothing outside this package changes it.
var maxRepairMemory uint64 = MaxRepairMemory

// InsufficientError is the typed "cannot repair" failure. It carries both
// halves of the arithmetic so the UI can say "needs 12 blocks, have 7" rather
// than "repair failed" (PLAN phase 7 task 4).
type InsufficientError struct {
	// Needed is the number of slices that would have to be reconstructed.
	Needed int
	// Available is the number of recovery slices the set actually has.
	Available int
}

// Deficit is how many more recovery blocks the set would need. It is always
// positive for an error that was actually returned.
func (e *InsufficientError) Deficit() int { return e.Needed - e.Available }

func (e *InsufficientError) Error() string {
	return fmt.Sprintf("par2: repair needs %d recovery blocks, only %d available (%d short)",
		e.Needed, e.Available, e.Deficit())
}

// Unwrap is ErrUnrepairable, the sentinel a pipeline branches on.
func (e *InsufficientError) Unwrap() error { return ErrUnrepairable }

// ChecksumError is a reconstructed file whose MD5 does not match the one the
// set's file description packet declared. It aborts the whole repair: a
// mismatch here means the recovered bytes are wrong, and writing them would be
// worse than leaving the damage in place.
type ChecksumError struct {
	// Name is the file as the par2 set names it.
	Name string
	// Expected is the MD5 from the file description packet.
	Expected [16]byte
	// Actual is the MD5 of the bytes the repair produced.
	Actual [16]byte
}

func (e *ChecksumError) Error() string {
	return fmt.Sprintf("par2: %s: repaired file md5 mismatch: expected %x, got %x",
		e.Name, e.Expected, e.Actual)
}

// Unwrap is ErrRepairFailed.
func (e *ChecksumError) Unwrap() error { return ErrRepairFailed }
