-- Phase 13: download concurrency caps — `download_clients` learns how many
-- downloads Caravan may have in flight at one client (SPEC §5.1).
--
-- The other two caps in this feature — the global one and the per-embedded-
-- engine ones — are settings keys, because there is exactly one of each and
-- `settings` is where Caravan's single-valued configuration lives. This one
-- cannot be: there is one cap per configured client row, it belongs to that
-- row's lifetime, and it has to disappear when the client is deleted. A
-- settings key per client id would be a sparse keyed table pretending to be a
-- scalar, and would leak a stale key for every client the user ever removed.
--
-- So it is a column, which is what a per-row attribute is.
--
-- Zero means unlimited, matching every other cap in this feature and the rate
-- limits above it: a Caravan that has never been told a number behaves exactly
-- as it did before this migration, which is the only safe default for a
-- setting that can stop downloads from starting.
ALTER TABLE download_clients ADD COLUMN max_concurrent INTEGER NOT NULL DEFAULT 0;
