-- Retire the adult module's two switches.
--
-- 0027 read both of these to build the per-library state that replaced them: an
-- adult library's `active` came out of `settings.adult_enabled`, and its
-- `library_access` roster came out of `users.adult_access`. Neither has had a
-- writer since the access endpoints replaced the module switch, so what they
-- hold now is whatever the install was carrying the day it upgraded, frozen.
--
-- Frozen is not harmless. A column named `adult_access` is exactly the thing a
-- future reader wires back up — it reads like the answer to "may this account
-- see the adult library", it is right there on the row, and it is stale by
-- construction: an account whose grant was revoked on the Access card still
-- carries a 1 in it. The only way to make that mistake unmakeable is to remove
-- the column.
--
-- THIS MIGRATION MUST NEVER BE FOLDED INTO 0027. An old backup re-migrates from
-- its own schema version on every open, so 0027 has to be able to read these two
-- forever; it runs first and reads them, and only then does this file remove
-- them. Merged, the pair would delete what it was about to read, and every
-- backup older than 0027 would upgrade with its adult library dark and its
-- grants gone.

-- ---------------------------------------------------------------------------
-- settings.adult_enabled
-- ---------------------------------------------------------------------------
--
-- DELETE rather than "leave it, nothing reads it": the settings table is a
-- key-value store an admin can be shown, and a row saying the adult module is
-- switched on, on a server where the module is a library like any other, is a
-- lie with a UI waiting to render it. 0011 removed the folded-in `password_hash`
-- for the same reason — a superseded credential left lying in `settings` is a
-- second, unreachable answer to a question something will ask again.
DELETE FROM settings WHERE key = 'adult_enabled';

-- ---------------------------------------------------------------------------
-- users.adult_access
-- ---------------------------------------------------------------------------
--
-- DROP COLUMN is available (SQLite 3.35+; modernc.org/sqlite v1.55 is well past
-- it) and it is safe here for the reason SQLite requires: the column is in no
-- index, no UNIQUE, no CHECK, no partial index and no generated column. 0011
-- builds `users` with a PRIMARY KEY on `id`, a UNIQUE on `username` and a CHECK
-- on `role`, and 0013 added `adult_access` alone with a plain DEFAULT 0. Nothing
-- has indexed it since — the grant is asked about per library now, and that
-- question is `idx_library_access_user`'s.
ALTER TABLE users DROP COLUMN adult_access;
